version: "3.8"

networks:
  inception:
    name: inception
volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/arash/Desktop/inception/volumes/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/arash/Desktop/inception/volumes/mariadb
                        o: bind
                        type: none
services:
  nginx:
    container_name: nginx
    build: ./nginx/.
    #image: nginx:42
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./wordpress/.
    #image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
   container_name: mariadb
   image: my_mariadb
   build: ./mariadb/.
   networks:
   - inception
   ports:
    - "3306:3306"
   restart: always
   env_file:
   - .env
   volumes:
   - mariadb:/var/lib/mysql
  # ftp:
  #   container_name: ftp
  #   build: ./bonus/ftp/.
  #   image: ftp:42
  #   depends_on:
  #     - wordpress
  #   volumes:
  #     - wordpress:/var/www/html
  #   env_file:
  #     - .env
  #   ports:
  #     - "21:21"
  #     - "20:20"
  #     - "40000-40005:40000-40005"
  #   networks:
  #     - inception
  #   restart: always
  adminer:
    container_name: adminer
    build: ./bonus/adminer/.
    image: adminer:42
    depends_on:
      - mariadb
    ports:
      - "600:80"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always
  redis:
    container_name: redis
    build: ./bonus/redis/.
    image: redis:42
    volumes:
     - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
  # website:
  #   container_name: website
  #   build: ./requirements/bonus/websites/.
  #   image: website:42
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - inception
  #   restart: always