version: "3.8"

networks:
  inception:
    name: inception
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/arash/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/arash/data/mariadb
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
        ipv4_address: 172.20.0.2
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/bonus/wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
        ipv4_address: 172.20.0.3
    env_file:
      - .env
    restart: always
  mariadb:
   container_name: mariadb
   image: my_mariadb
   build: ./requirements/mariadb/.
   networks:
     inception:
       ipv4_address: 172.20.0.4
   ports:
     - "3305:3306"
   restart: always
   env_file:
     - .env
   volumes:
     - mariadb:/var/lib/mysql

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/.
    image: ftp:42
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    networks:
     inception:
       ipv4_address: 172.20.0.5
    restart: always
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    image: adminer:42
    depends_on:
      - mariadb
    ports:
      - "600:80"
    networks:
     inception:
       ipv4_address: 172.20.0.6
    volumes:
      - wordpress:/var/www/html
    restart: always
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    image: redis:42
    volumes:
     - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
     inception:
       ipv4_address: 172.20.0.7
    ports:
      - "6380:6379"
    restart: always
  website:
    container_name: website
    build: ./requirements/bonus/jswebsite/.
    image: jswebsite:42
    ports:
      - "3000:3000"
    networks:
     inception:
       ipv4_address: 172.20.0.8
    restart: always
