version: "3.8"

networks:
  inception:
    name: inception
volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/arash/Desktop/inception/volumes/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/arash/Desktop/inception/volumes/mariadb
                        o: bind
                        type: none
services:
  nginx:
    container_name: nginx
    build: ./nginx/.
    #image: nginx:42
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./wordpress/.
    #image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
   container_name: mariadb
   image: my_mariadb
   build: ./mariadb/.
   networks:
   - inception
   ports:
    - "3306:3306"
   restart: always
   env_file:
   - .env
   volumes:
   - mariadb:/var/lib/mysql
